# Generated by Django 5.2.14 on 2026-06-03 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0008_historicaluser_churn_digest_monthly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Identificação humana do token (ex.: 'Claude Desktop do Paulo').", max_length=120)),
                ('prefix', models.CharField(db_index=True, help_text='Início do token em claro — só para exibição/auditoria.', max_length=32)),
                ('token_hash', models.CharField(help_text='SHA-256 do token. O segredo cru nunca é persistido.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Token MCP',
                'verbose_name_plural': 'Tokens MCP',
                'indexes': [models.Index(fields=['organization', 'is_active'], name='mcp_mcptoke_organiz_0bcd91_idx')],
            },
        ),
    ]
