# Generated by Django 5.2.14 on 2026-06-02 01:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0006_alter_historicalorganizationdatasource_capability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLead',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID do candidato no sistema externo (opaco — string).', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('origin', models.CharField(blank=True, default='', help_text='Canal de origem (indicação, site, redes sociais...).', max_length=128)),
                ('salesperson_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Em contato'), ('CONVERTED', 'Convertido'), ('LOST', 'Perdido'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('created_at_source', models.DateTimeField(blank=True, null=True)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'historical Lead',
                'verbose_name_plural': 'historical Leads',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID do candidato no sistema externo (opaco — string).', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('origin', models.CharField(blank=True, default='', help_text='Canal de origem (indicação, site, redes sociais...).', max_length=128)),
                ('salesperson_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Em contato'), ('CONVERTED', 'Convertido'), ('LOST', 'Perdido'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('created_at_source', models.DateTimeField(blank=True, null=True)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOpportunity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('lead_external_id', models.CharField(db_index=True, max_length=128)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Em andamento'), ('WON', 'Ganha'), ('LOST', 'Perdida'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('loss_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at_source', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization', verbose_name='Organização')),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.lead')),
            ],
            options={
                'verbose_name': 'historical Negociação',
                'verbose_name_plural': 'historical Negociações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('lead_external_id', models.CharField(db_index=True, max_length=128)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Em andamento'), ('WON', 'Ganha'), ('LOST', 'Perdida'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('loss_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at_source', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='sales.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Negociação',
                'verbose_name_plural': 'Negociações',
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'status'], name='sales_lead_organiz_0c67fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'created_at_source'], name='sales_lead_organiz_2c74a2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'origin'], name='sales_lead_organiz_30e329_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'external_id'), name='unique_lead_per_source'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['organization', 'status'], name='sales_oppor_organiz_b4c27c_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['organization', 'created_at_source'], name='sales_oppor_organiz_cc7eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['organization', 'source_type', 'lead_external_id'], name='sales_oppor_organiz_d26a5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'external_id'), name='unique_opportunity_per_source'),
        ),
    ]
