# Generated by Django 5.2.14 on 2026-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalopportunity',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
    ]
