# Generated by Django 5.2.14 on 2026-05-28 19:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContract',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('customer_external_id', models.CharField(db_index=True, max_length=128)),
                ('plan_name', models.CharField(max_length=128)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('BLOCKED', 'Bloqueado'), ('CANCELED', 'Cancelado'), ('AWAITING_INSTALL', 'Aguardando instalação'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=24)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'historical Contrato',
                'verbose_name_plural': 'historical Contratos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('customer_external_id', models.CharField(db_index=True, max_length=128)),
                ('plan_name', models.CharField(max_length=128)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('BLOCKED', 'Bloqueado'), ('CANCELED', 'Cancelado'), ('AWAITING_INSTALL', 'Aguardando instalação'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=24)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'indexes': [models.Index(fields=['organization', 'customer'], name='customers_c_organiz_a5a0cd_idx'), models.Index(fields=['organization', 'status'], name='customers_c_organiz_af0749_idx'), models.Index(fields=['organization', 'source_type', 'customer_external_id'], name='customers_c_organiz_133d9d_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_type', 'external_id'), name='unique_contract_per_source')],
            },
        ),
    ]
