# Generated by Django 5.2.14 on 2026-05-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_historicalcontract_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='monthly_amount_addons',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='monthly_amount_discounts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='monthly_amount_addons',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='monthly_amount_discounts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
