# Generated by Django 5.2.14 on 2026-06-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganizationdatasource',
            name='capability',
            field=models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos'), ('EXPENSES', 'Despesas'), ('TICKETS', 'Chamados'), ('CONNECTIONS', 'Conexões'), ('EQUIPMENT', 'Equipamentos em comodato'), ('LEADS', 'Leads (CRM)'), ('OPPORTUNITIES', 'Negociações (CRM)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationdatasource',
            name='capability',
            field=models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos'), ('EXPENSES', 'Despesas'), ('TICKETS', 'Chamados'), ('CONNECTIONS', 'Conexões'), ('EQUIPMENT', 'Equipamentos em comodato'), ('LEADS', 'Leads (CRM)'), ('OPPORTUNITIES', 'Negociações (CRM)')], max_length=32),
        ),
    ]
