# Generated by Django 5.2.14 on 2026-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='churn_digest_monthly',
            field=models.BooleanField(default=False, verbose_name='Digest mensal de risco de churn'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='churn_digest_weekly',
            field=models.BooleanField(default=False, verbose_name='Digest semanal de risco de churn'),
        ),
        migrations.AddField(
            model_name='user',
            name='churn_digest_monthly',
            field=models.BooleanField(default=False, verbose_name='Digest mensal de risco de churn'),
        ),
        migrations.AddField(
            model_name='user',
            name='churn_digest_weekly',
            field=models.BooleanField(default=False, verbose_name='Digest semanal de risco de churn'),
        ),
    ]
