# Generated by Django 5.2.14 on 2026-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_historicaluser_churn_digest_monthly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganizationdatasource',
            name='capability',
            field=models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos'), ('EXPENSES', 'Despesas'), ('TICKETS', 'Chamados'), ('ATENDIMENTO', 'Atendimentos (Opa! Suite)'), ('CONNECTIONS', 'Conexões'), ('BANDWIDTH', 'Consumo de banda'), ('EQUIPMENT', 'Equipamentos em comodato'), ('LEADS', 'Leads (CRM)'), ('OPPORTUNITIES', 'Negociações (CRM)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalorganizationdatasource',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationdatasource',
            name='capability',
            field=models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos'), ('EXPENSES', 'Despesas'), ('TICKETS', 'Chamados'), ('ATENDIMENTO', 'Atendimentos (Opa! Suite)'), ('CONNECTIONS', 'Conexões'), ('BANDWIDTH', 'Consumo de banda'), ('EQUIPMENT', 'Equipamentos em comodato'), ('LEADS', 'Leads (CRM)'), ('OPPORTUNITIES', 'Negociações (CRM)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationdatasource',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
    ]
