# Generated by Django 5.2.14 on 2026-07-30 17:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allowed_pages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_groups', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'Grupo de acesso',
                'verbose_name_plural': 'Grupos de acesso',
            },
        ),
        migrations.AddField(
            model_name='historicalorganizationmembership',
            name='access_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.accessgroup'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='access_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='tenancy.accessgroup'),
        ),
        migrations.CreateModel(
            name='HistoricalAccessGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allowed_pages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'historical Grupo de acesso',
                'verbose_name_plural': 'historical Grupos de acesso',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='accessgroup',
            index=models.Index(fields=['organization'], name='tenancy_acc_organiz_e27258_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_access_group_name_per_org'),
        ),
    ]
