"""Nova capability OPTICAL_SIGNAL no catálogo (#148).

Só `choices` — nenhuma mudança de coluna no banco. Habilitar sinal óptico é
opt-in por organização porque é a única leitura do projeto que consulta
equipamento de produção ao vivo (a OLT).
"""

# Generated by Django 5.2.14 on 2026-09-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0013_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganizationdatasource',
            name='capability',
            field=models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos'), ('EXPENSES', 'Despesas'), ('TICKETS', 'Chamados'), ('ATENDIMENTO', 'Atendimentos (Opa! Suite)'), ('MENSAGENS', 'Mensagens de atendimento (Opa! Suite)'), ('CONNECTIONS', 'Conexões'), ('BANDWIDTH', 'Consumo de banda'), ('NETWORK_ELEMENTS', 'Topologia de rede'), ('OPTICAL_SIGNAL', 'Sinal óptico da ONU'), ('EQUIPMENT', 'Equipamentos em comodato'), ('LEADS', 'Leads (CRM)'), ('OPPORTUNITIES', 'Negociações (CRM)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='organizationdatasource',
            name='capability',
            field=models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos'), ('EXPENSES', 'Despesas'), ('TICKETS', 'Chamados'), ('ATENDIMENTO', 'Atendimentos (Opa! Suite)'), ('MENSAGENS', 'Mensagens de atendimento (Opa! Suite)'), ('CONNECTIONS', 'Conexões'), ('BANDWIDTH', 'Consumo de banda'), ('NETWORK_ELEMENTS', 'Topologia de rede'), ('OPTICAL_SIGNAL', 'Sinal óptico da ONU'), ('EQUIPMENT', 'Equipamentos em comodato'), ('LEADS', 'Leads (CRM)'), ('OPPORTUNITIES', 'Negociações (CRM)')], max_length=32),
        ),
    ]
