# Generated by Django 5.2.14 on 2026-09-19 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0014_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_key', models.CharField(help_text='Painel que esta TV abre — uma TV do NOC não abre o executivo.', max_length=32)),
                ('name', models.CharField(blank=True, default='', help_text="Como a sala chama esta TV ('TV da bancada').", max_length=120)),
                ('code', models.CharField(help_text='Código curto mostrado na TV. Efêmero e de uso único.', max_length=12, unique=True)),
                ('device_token_hash', models.CharField(max_length=64)),
                ('display_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_displays', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_devices', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'Dispositivo de painel',
                'verbose_name_plural': 'Dispositivos de painel',
                'indexes': [models.Index(fields=['organization', 'revoked_at'], name='tenancy_dis_organiz_e9273a_idx')],
            },
        ),
    ]
