# Generated by Django 5.2.14 on 2026-09-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0015_displaydevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaydevice',
            name='code',
            field=models.CharField(blank=True, help_text='Código curto mostrado na TV. Efêmero e de uso único — vira NULL quando é consumido, porque código que sobrevive ao uso dá a alguém uma segunda chance de aprovar a mesma TV.', max_length=12, null=True, unique=True),
        ),
    ]
