# Generated by Django 5.2.14 on 2026-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0016_alter_displaydevice_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='URL pública do logo, exibida no painel de parede.', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='URL pública do logo, exibida no painel de parede.', max_length=500),
        ),
    ]
