# Generated by Django 5.2.14 on 2026-06-08 19:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_contract_source_type_and_more'),
        ('tenancy', '0009_alter_historicalorganizationdatasource_capability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID do setor no sistema externo (opaco — string).', max_length=128)),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Departamento de atendimento',
                'verbose_name_plural': 'Departamentos de atendimento',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID do atendimento no sistema externo (opaco — string).', max_length=128)),
                ('customer_external_id', models.CharField(blank=True, db_index=True, default='', help_text='ID opaco do cliente na fonte (nao bate com Customer.external_id).', max_length=128)),
                ('customer_document', models.CharField(blank=True, db_index=True, default='', help_text='CPF/CNPJ normalizado — ponte logica pro Customer.', max_length=14)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('departamento_external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('atendente_external_id', models.CharField(blank=True, default='', max_length=128)),
                ('atendente_nome', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em atendimento'), ('CLOSED', 'Finalizado'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('canal', models.CharField(blank=True, default='', max_length=64)),
                ('protocol', models.CharField(blank=True, default='', max_length=128)),
                ('motivos', models.JSONField(blank=True, default=list)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Nota humana likert 1-5 (so vem em GET populado).', null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='atendimento.departamento')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAtendimento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID do atendimento no sistema externo (opaco — string).', max_length=128)),
                ('customer_external_id', models.CharField(blank=True, db_index=True, default='', help_text='ID opaco do cliente na fonte (nao bate com Customer.external_id).', max_length=128)),
                ('customer_document', models.CharField(blank=True, db_index=True, default='', help_text='CPF/CNPJ normalizado — ponte logica pro Customer.', max_length=14)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('departamento_external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('atendente_external_id', models.CharField(blank=True, default='', max_length=128)),
                ('atendente_nome', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em atendimento'), ('CLOSED', 'Finalizado'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('canal', models.CharField(blank=True, default='', max_length=64)),
                ('protocol', models.CharField(blank=True, default='', max_length=128)),
                ('motivos', models.JSONField(blank=True, default=list)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Nota humana likert 1-5 (so vem em GET populado).', null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer')),
                ('departamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='atendimento.departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'historical Atendimento',
                'verbose_name_plural': 'historical Atendimentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID da mensagem no sistema externo (opaco — string).', max_length=128)),
                ('atendimento_external_id', models.CharField(db_index=True, max_length=128)),
                ('direction', models.CharField(choices=[('CLIENT', 'Cliente'), ('AGENT', 'Atendente'), ('SYSTEM', 'Sistema'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('tipo', models.CharField(blank=True, default='', max_length=64)),
                ('texto', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='atendimento.atendimento')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Mensagem de atendimento',
                'verbose_name_plural': 'Mensagens de atendimento',
            },
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['organization', 'source_type'], name='atendimento_organiz_3df443_idx'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'external_id'), name='unique_atendimento_departamento_per_source'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['organization', 'status'], name='atendimento_organiz_3a36b7_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['organization', 'opened_at'], name='atendimento_organiz_105352_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['organization', 'departamento_external_id'], name='atendimento_organiz_880e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['organization', 'customer_document'], name='atendimento_organiz_877051_idx'),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'external_id'), name='unique_atendimento_per_source'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['organization', 'source_type', 'atendimento_external_id'], name='atendimento_organiz_551d58_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['organization', 'sent_at'], name='atendimento_organiz_560a6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mensagem',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'external_id'), name='unique_atendimento_mensagem_per_source'),
        ),
    ]
