# Generated by Django 5.2.14 on 2026-08-04 20:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_motivo'),
        ('tenancy', '0011_organizationinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEventoRede',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('tipo', models.CharField(choices=[('ROMPIMENTO', 'Rompimento'), ('MANUTENCAO', 'Manutenção programada'), ('QUEDA_LINK', 'Queda de link'), ('ATUALIZACAO', 'Atualização'), ('OUTRO', 'Outro')], default='OUTRO', help_text='Natureza do evento (define a cor no gráfico).', max_length=16)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(help_text='Início do evento.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Fim do evento; vazio = evento pontual.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'historical Evento de rede',
                'verbose_name_plural': 'historical Eventos de rede',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EventoRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ROMPIMENTO', 'Rompimento'), ('MANUTENCAO', 'Manutenção programada'), ('QUEDA_LINK', 'Queda de link'), ('ATUALIZACAO', 'Atualização'), ('OUTRO', 'Outro')], default='OUTRO', help_text='Natureza do evento (define a cor no gráfico).', max_length=16)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(help_text='Início do evento.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Fim do evento; vazio = evento pontual.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_rede', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Evento de rede',
                'verbose_name_plural': 'Eventos de rede',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['organization', 'started_at'], name='atendimento_organiz_febbaf_idx')],
            },
        ),
    ]
