# Generated by Django 5.2.14 on 2026-09-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_historicaleventorede_eventorede'),
        ('tenancy', '0011_organizationinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalComunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID do canal no sistema externo (opaco — string).', max_length=128)),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('canal', models.CharField(blank=True, default='', max_length=64)),
                ('integracao', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, default='', help_text='Status na fonte: A = ativo, I = inativo.', max_length=8)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Canal de comunicação',
                'verbose_name_plural': 'Canais de comunicação',
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='canal_external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='origem_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='origem_tipo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalatendimento',
            name='canal_external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalatendimento',
            name='origem_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalatendimento',
            name='origem_tipo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='canal_external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Canal/numero por onde a mensagem passou (`canalComunicacao`).', max_length=128),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='fora_janela_24h',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['organization', 'sent_at', 'direction'], name='atendimento_organiz_4dfd06_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['organization', 'canal_external_id', 'sent_at'], name='atendimento_organiz_000420_idx'),
        ),
        migrations.AddField(
            model_name='canalcomunicacao',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização'),
        ),
        migrations.AddIndex(
            model_name='canalcomunicacao',
            index=models.Index(fields=['organization', 'source_type'], name='atendimento_organiz_2d2b2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='canalcomunicacao',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'external_id'), name='unique_atendimento_canal_per_source'),
        ),
    ]
