# Generated by Django 5.2.14 on 2026-09-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_backfill_canal_origem_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorede',
            name='element_external_id',
            field=models.CharField(blank=True, default='', help_text='Id do elemento no IXC. Vazio = todo o escopo.', max_length=128),
        ),
        migrations.AddField(
            model_name='eventorede',
            name='scope',
            field=models.CharField(blank=True, default='', help_text='CTO, PON, OLT ou POP. Vazio = toda a rede.', max_length=8),
        ),
        migrations.AddField(
            model_name='historicaleventorede',
            name='element_external_id',
            field=models.CharField(blank=True, default='', help_text='Id do elemento no IXC. Vazio = todo o escopo.', max_length=128),
        ),
        migrations.AddField(
            model_name='historicaleventorede',
            name='scope',
            field=models.CharField(blank=True, default='', help_text='CTO, PON, OLT ou POP. Vazio = toda a rede.', max_length=8),
        ),
    ]
