# Generated by Django 5.2.14 on 2026-09-09 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_connection_topologia_e_quedas'),
        ('tenancy', '0013_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, help_text='Preenchido quando ≥90% dos afetados voltou (§6).', null=True)),
                ('last_detected_at', models.DateTimeField(help_text='Última rodada do poll em que o detector ainda viu esta massiva.')),
                ('scope', models.CharField(choices=[('CTO', 'Caixa (CTO)'), ('PON', 'Porta PON'), ('OLT', 'Transmissor (OLT)'), ('POP', 'POP'), ('GEO', 'Proximidade geográfica')], max_length=8)),
                ('element_external_id', models.CharField(blank=True, default='', max_length=128)),
                ('element_label', models.CharField(blank=True, default='', max_length=255)),
                ('suspected_segment_label', models.CharField(blank=True, default='', help_text="Trecho suspeito entre caixas — nunca 'cabo X', que a API não permite afirmar (§2.3).", max_length=255)),
                ('confidence', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], max_length=8)),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('restored_count', models.PositiveIntegerField(default=0)),
                ('affected_fraction', models.FloatField(default=0.0, help_text='Afetados / logins ativos do elemento em escopo.')),
                ('mrr_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
                ('suspected_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outage_events', to='network.networkelement')),
            ],
            options={
                'verbose_name': 'Massiva',
                'verbose_name_plural': 'Massivas',
            },
        ),
        migrations.CreateModel(
            name='OutageAffectedLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(blank=True, default='', max_length=128)),
                ('dropped_at', models.DateTimeField()),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('drop_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outage_links', to='network.connectiondropevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
                ('outage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_logins', to='network.outageevent')),
            ],
            options={
                'verbose_name': 'Cliente afetado por massiva',
                'verbose_name_plural': 'Clientes afetados por massiva',
            },
        ),
        migrations.CreateModel(
            name='ConnectionPollState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_at', models.DateTimeField(help_text='Instante da primeira leitura de status — antes disso, nada é queda.')),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Estado do poll de conexões',
                'verbose_name_plural': 'Estados do poll de conexões',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='unique_connection_poll_state_per_org')],
            },
        ),
        migrations.AddIndex(
            model_name='outageevent',
            index=models.Index(fields=['organization', 'ended_at'], name='network_out_organiz_53b66f_idx'),
        ),
        migrations.AddIndex(
            model_name='outageaffectedlogin',
            index=models.Index(fields=['organization', 'outage'], name='network_out_organiz_30cb1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='outageaffectedlogin',
            constraint=models.UniqueConstraint(fields=('outage', 'drop_event'), name='unique_affected_drop_per_outage'),
        ),
    ]
