"""Sinal óptico e causa de queda por ONU (#148).

**Só schema — sem backfill, e isso é a decisão, não um esquecimento.** A
ferramenta de massivas é de tempo real e não responde pergunta sobre o passado
(`docs/massivas-plano.md` §1 e §10.5): as colunas nascem vazias, a leitura
passiva diária preenche a linha de base na primeira rodada e a medição ativa
preenche o "depois" quando um cliente volta. Ir atrás de histórico aqui seria
inventar leituras que ninguém observou.

Todo campo de potência é anulável porque **zero não é potência, é ausência de
leitura**: `sinal_rx = "0.00"` vem em 1.391 dos 4.554 registros do IXC, e ~30%
das ONUs não reportam sinal nenhum. Um default de 0.0 mostraria 24 dB de perda
em cada cliente que caiu.
"""

# Generated by Django 5.2.14 on 2026-09-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_massivas_e_estado_do_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='onu_external_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='connection',
            name='onu_last_drop_cause',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='connection',
            name='onu_last_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='onu_run_state',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='connection',
            name='signal_measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='signal_rx',
            field=models.FloatField(blank=True, help_text='Potência de recepção (dBm). Nulo = sem leitura.', null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='signal_tx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectiondropevent',
            name='signal_after_measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectiondropevent',
            name='signal_before_measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectiondropevent',
            name='signal_rx_after',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectiondropevent',
            name='signal_rx_before',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconnection',
            name='onu_external_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalconnection',
            name='onu_last_drop_cause',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalconnection',
            name='onu_last_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconnection',
            name='onu_run_state',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalconnection',
            name='signal_measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalconnection',
            name='signal_rx',
            field=models.FloatField(blank=True, help_text='Potência de recepção (dBm). Nulo = sem leitura.', null=True),
        ),
        migrations.AddField(
            model_name='historicalconnection',
            name='signal_tx',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
