# Generated by Django 5.2.14 on 2026-09-19 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_connection_onu_external_id_and_more'),
        ('tenancy', '0014_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkElementGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este traçado.', max_length=32)),
                ('kind', models.CharField(choices=[('CTO', 'Caixa de atendimento (CTO)'), ('POP', 'Ponto de presença (POP)'), ('PON', 'Porta PON'), ('OLT', 'Transmissor (OLT)'), ('CABLE', 'Cabo')], max_length=16)),
                ('external_id', models.CharField(help_text='ID do elemento na origem — o mesmo de NetworkElement.', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('project_external_id', models.CharField(blank=True, default='', max_length=128)),
                ('points', models.JSONField(blank=True, default=list, help_text='[[lat, lon], ...] na ordem do traçado.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Traçado de elemento',
                'verbose_name_plural': 'Traçados de elementos',
                'indexes': [models.Index(fields=['organization', 'kind'], name='network_net_organiz_e346a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_type', 'kind', 'external_id'), name='unique_element_geometry_per_source')],
            },
        ),
    ]
