# Generated by Django 5.2.14 on 2026-09-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_networkelementgeometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkelementgeometry',
            name='type_name',
            field=models.CharField(blank=True, default='', help_text='Nome do tipo na origem — é ele que diz a classe do cabo, e não a descrição do elemento.', max_length=255),
        ),
    ]
