# Generated by Django 5.2.14 on 2026-09-19 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_networkelementgeometry_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outageevent',
            name='cause_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='cause_confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Quem preencheu. Rótulo sem autor não se audita.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outage_causes_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='cause_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='cause_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='confirmed_cause',
            field=models.CharField(blank=True, choices=[('ROMPIMENTO', 'Rompimento de fibra'), ('ENERGIA', 'Falta de energia'), ('EQUIPAMENTO', 'Equipamento (OLT)'), ('MANUTENCAO', 'Manutenção programada'), ('FALSO_POSITIVO', 'Falso positivo')], default='', help_text='O que a massiva era de verdade — preenchido por pessoa, nunca pelo sistema.', max_length=20),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='maintenance_event_id',
            field=models.PositiveIntegerField(blank=True, help_text='EventoRede que explica esta massiva — gravado no nascimento dela.', null=True),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='maintenance_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
