# Generated by Django 5.2.14 on 2026-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_outageevent_cause_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='kind',
            field=models.CharField(choices=[('CTO', 'Caixa de atendimento (CTO)'), ('POP', 'Ponto de presença (POP)'), ('PON', 'Porta PON'), ('OLT', 'Transmissor (OLT)'), ('CABLE', 'Cabo'), ('SPLICE', 'Caixa de emenda')], max_length=16),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='parent_kind',
            field=models.CharField(blank=True, choices=[('CTO', 'Caixa de atendimento (CTO)'), ('POP', 'Ponto de presença (POP)'), ('PON', 'Porta PON'), ('OLT', 'Transmissor (OLT)'), ('CABLE', 'Cabo'), ('SPLICE', 'Caixa de emenda')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='networkelementgeometry',
            name='kind',
            field=models.CharField(choices=[('CTO', 'Caixa de atendimento (CTO)'), ('POP', 'Ponto de presença (POP)'), ('PON', 'Porta PON'), ('OLT', 'Transmissor (OLT)'), ('CABLE', 'Cabo'), ('SPLICE', 'Caixa de emenda')], max_length=16),
        ),
    ]
