# Generated by Django 5.2.14 on 2026-09-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_outageevent_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outageevent',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
