# Generated by Django 5.2.14 on 2026-09-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_outageevent_escalated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='outageevent',
            name='cause_waived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='cause_waived_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
