# Generated by Django 5.2.14 on 2026-09-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_outageevent_cause_waived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outageevent',
            name='acknowledged_by_display',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
