# Generated by Django 5.2.14 on 2026-09-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_outageevent_closed_manual_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkelement',
            name='kind',
            field=models.CharField(choices=[('CTO', 'Caixa de atendimento (CTO)'), ('POP', 'Ponto de presença (POP)'), ('PON', 'Porta PON'), ('OLT', 'Transmissor (OLT)'), ('CABLE', 'Cabo'), ('SPLICE', 'Caixa de emenda'), ('SPLITTER', 'Splitter'), ('POLE', 'Poste')], max_length=16),
        ),
        migrations.AlterField(
            model_name='networkelement',
            name='parent_kind',
            field=models.CharField(blank=True, choices=[('CTO', 'Caixa de atendimento (CTO)'), ('POP', 'Ponto de presença (POP)'), ('PON', 'Porta PON'), ('OLT', 'Transmissor (OLT)'), ('CABLE', 'Cabo'), ('SPLICE', 'Caixa de emenda'), ('SPLITTER', 'Splitter'), ('POLE', 'Poste')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='networkelementgeometry',
            name='kind',
            field=models.CharField(choices=[('CTO', 'Caixa de atendimento (CTO)'), ('POP', 'Ponto de presença (POP)'), ('PON', 'Porta PON'), ('OLT', 'Transmissor (OLT)'), ('CABLE', 'Cabo'), ('SPLICE', 'Caixa de emenda'), ('SPLITTER', 'Splitter'), ('POLE', 'Poste')], max_length=16),
        ),
    ]
