# Generated by Django 5.2.14 on 2026-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_alter_networkelement_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkelementgeometry',
            name='coordinate_ids',
            field=models.JSONField(blank=True, default=list, help_text='id da coordenada na origem, um por vértice, na ordem de points.'),
        ),
    ]
