# Generated by Django 5.2.14 on 2026-09-30 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_networkelementgeometry_coordinate_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outageevent',
            name='break_evaluation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='break_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='break_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='break_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outageevent',
            name='break_recorded_by',
            field=models.ForeignKey(blank=True, help_text='Quem registrou. Gabarito sem autor não se audita.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outage_breaks_recorded', to=settings.AUTH_USER_MODEL),
        ),
    ]
