# Generated by Django 5.2.14 on 2026-06-02 01:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_add_addon_discount_amounts'),
        ('tenancy', '0005_alter_historicalorganizationdatasource_capability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContractEquipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID do comodato no sistema externo (opaco — string).', max_length=128)),
                ('contract_external_id', models.CharField(db_index=True, max_length=128)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('serial', models.CharField(blank=True, default='', max_length=128)),
                ('mac', models.CharField(blank=True, default='', max_length=64)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Em campo'), ('RETURNED', 'Devolvido'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contract', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.contract')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'historical Equipamento em comodato',
                'verbose_name_plural': 'historical Equipamentos em comodato',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ContractEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID do comodato no sistema externo (opaco — string).', max_length=128)),
                ('contract_external_id', models.CharField(db_index=True, max_length=128)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('serial', models.CharField(blank=True, default='', max_length=128)),
                ('mac', models.CharField(blank=True, default='', max_length=64)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Em campo'), ('RETURNED', 'Devolvido'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='customers.contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Equipamento em comodato',
                'verbose_name_plural': 'Equipamentos em comodato',
                'indexes': [models.Index(fields=['organization', 'status'], name='inventory_c_organiz_dc0449_idx'), models.Index(fields=['organization', 'source_type', 'contract_external_id'], name='inventory_c_organiz_406121_idx'), models.Index(fields=['organization', 'serial'], name='inventory_c_organiz_419822_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_type', 'external_id'), name='unique_equipment_per_source')],
            },
        ),
    ]
