# Generated by Django 5.2.14 on 2026-05-30 21:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_add_addon_discount_amounts'),
        ('tenancy', '0003_initial_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID do chamado no sistema externo (opaco — string).', max_length=128)),
                ('customer_external_id', models.CharField(db_index=True, max_length=128)),
                ('subject_id', models.CharField(blank=True, default='', max_length=128)),
                ('sector', models.CharField(blank=True, default='', max_length=128)),
                ('technician_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em execucao'), ('CLOSED', 'Fechado'), ('FORWARDED', 'Encaminhado'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('LOW', 'Baixa'), ('URGENT', 'Urgente'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('protocol', models.CharField(blank=True, default='', max_length=128)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'historical Chamado',
                'verbose_name_plural': 'historical Chamados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], help_text='Sistema externo que originou este registro.', max_length=32)),
                ('external_id', models.CharField(help_text='ID do chamado no sistema externo (opaco — string).', max_length=128)),
                ('customer_external_id', models.CharField(db_index=True, max_length=128)),
                ('subject_id', models.CharField(blank=True, default='', max_length=128)),
                ('sector', models.CharField(blank=True, default='', max_length=128)),
                ('technician_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em execucao'), ('CLOSED', 'Fechado'), ('FORWARDED', 'Encaminhado'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'Alta'), ('LOW', 'Baixa'), ('URGENT', 'Urgente'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('protocol', models.CharField(blank=True, default='', max_length=128)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'indexes': [models.Index(fields=['organization', 'status'], name='helpdesk_ti_organiz_310b74_idx'), models.Index(fields=['organization', 'opened_at'], name='helpdesk_ti_organiz_46f312_idx'), models.Index(fields=['organization', 'source_type', 'customer_external_id'], name='helpdesk_ti_organiz_822e82_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_type', 'external_id'), name='unique_ticket_per_source')],
            },
        ),
    ]
