# Generated by Django 5.2.14 on 2026-06-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial_ticket'),
        ('tenancy', '0008_historicaluser_churn_digest_monthly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsLookupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_map', models.JSONField(default=dict, help_text='su_oss_assunto.id → assunto (tipo de OS)', verbose_name='Mapa de assuntos')),
                ('technician_map', models.JSONField(default=dict, help_text='funcionarios.id → funcionario (nome do técnico)', verbose_name='Mapa de técnicos')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='os_lookup_cache', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Cache de lookups de OS IXC',
                'verbose_name_plural': 'Caches de lookups de OS IXC',
            },
        ),
    ]
