# Generated by Django 5.2.14 on 2026-05-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32)),
                ('capability', models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos')], max_length=32)),
                ('last_processed_at', models.DateTimeField(blank=True, help_text="Maior data_alteracao/updated_at processada com sucesso. Próximo incremental usa como 'since'.", null=True)),
                ('last_external_id', models.CharField(blank=True, default='', help_text='Último external_id processado — backup pra fontes que não têm updated_at confiável.', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_checkpoints', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'Checkpoint de sync',
                'verbose_name_plural': 'Checkpoints de sync',
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_type', 'capability'), name='unique_checkpoint_per_source_capability')],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32)),
                ('capability', models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos')], max_length=32)),
                ('mode', models.CharField(choices=[('BOOTSTRAP', 'Bootstrap (carga total inicial)'), ('INCREMENTAL', 'Incremental (delta desde último checkpoint)')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Em execução'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'Job de sync',
                'verbose_name_plural': 'Jobs de sync',
                'indexes': [models.Index(fields=['organization', 'source_type', 'capability', '-created_at'], name='sync_syncjo_organiz_be04e1_idx'), models.Index(fields=['status', '-created_at'], name='sync_syncjo_status_e7912b_idx')],
            },
        ),
    ]
