# Generated by Django 5.2.14 on 2026-08-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_alter_synccheckpoint_capability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccheckpoint',
            name='consecutive_empty_runs',
            field=models.PositiveIntegerField(default=0, help_text='Rodadas INCREMENTAIS seguidas que não importaram nada. Zerado assim que um registro entra. Uma rodada vazia é rotina; dezenas seguidas foram seis semanas de caixa faltando sem ninguém ver (#132).'),
        ),
    ]
