# Generated by Django 5.2.14 on 2026-09-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_checkpoint_empty_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synccheckpoint',
            name='capability',
            field=models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos'), ('EXPENSES', 'Despesas'), ('TICKETS', 'Chamados'), ('ATENDIMENTO', 'Atendimentos (Opa! Suite)'), ('MENSAGENS', 'Mensagens de atendimento (Opa! Suite)'), ('CONNECTIONS', 'Conexões'), ('BANDWIDTH', 'Consumo de banda'), ('EQUIPMENT', 'Equipamentos em comodato'), ('LEADS', 'Leads (CRM)'), ('OPPORTUNITIES', 'Negociações (CRM)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='capability',
            field=models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos'), ('EXPENSES', 'Despesas'), ('TICKETS', 'Chamados'), ('ATENDIMENTO', 'Atendimentos (Opa! Suite)'), ('MENSAGENS', 'Mensagens de atendimento (Opa! Suite)'), ('CONNECTIONS', 'Conexões'), ('BANDWIDTH', 'Consumo de banda'), ('EQUIPMENT', 'Equipamentos em comodato'), ('LEADS', 'Leads (CRM)'), ('OPPORTUNITIES', 'Negociações (CRM)')], max_length=32),
        ),
    ]
