"""Nova capability OPTICAL_SIGNAL no catálogo (#148) — só `choices`.

Nenhuma mudança de coluna. O sinal óptico não usa checkpoint incremental (a
leitura passiva é um pull completo diário), mas a capability entra no mesmo
vocabulário compartilhado.
"""

# Generated by Django 5.2.14 on 2026-09-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0009_alter_synccheckpoint_capability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synccheckpoint',
            name='capability',
            field=models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos'), ('EXPENSES', 'Despesas'), ('TICKETS', 'Chamados'), ('ATENDIMENTO', 'Atendimentos (Opa! Suite)'), ('MENSAGENS', 'Mensagens de atendimento (Opa! Suite)'), ('CONNECTIONS', 'Conexões'), ('BANDWIDTH', 'Consumo de banda'), ('NETWORK_ELEMENTS', 'Topologia de rede'), ('OPTICAL_SIGNAL', 'Sinal óptico da ONU'), ('EQUIPMENT', 'Equipamentos em comodato'), ('LEADS', 'Leads (CRM)'), ('OPPORTUNITIES', 'Negociações (CRM)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='capability',
            field=models.CharField(choices=[('CUSTOMERS', 'Clientes'), ('CONTRACTS', 'Contratos'), ('INVOICES', 'Faturas'), ('PAYMENTS', 'Pagamentos'), ('EXPENSES', 'Despesas'), ('TICKETS', 'Chamados'), ('ATENDIMENTO', 'Atendimentos (Opa! Suite)'), ('MENSAGENS', 'Mensagens de atendimento (Opa! Suite)'), ('CONNECTIONS', 'Conexões'), ('BANDWIDTH', 'Consumo de banda'), ('NETWORK_ELEMENTS', 'Topologia de rede'), ('OPTICAL_SIGNAL', 'Sinal óptico da ONU'), ('EQUIPMENT', 'Equipamentos em comodato'), ('LEADS', 'Leads (CRM)'), ('OPPORTUNITIES', 'Negociações (CRM)')], max_length=32),
        ),
    ]
