# Generated by Django 5.2.14 on 2026-05-29 12:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('tenancy', '0002_alter_historicalorganizationdatasource_capability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExpense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('paid_at', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Em aberto'), ('PAID', 'Pago'), ('CANCELED', 'Cancelado'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('payment_type', models.CharField(blank=True, default='', max_length=64)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'historical Despesa',
                'verbose_name_plural': 'historical Despesas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('paid_at', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Em aberto'), ('PAID', 'Pago'), ('CANCELED', 'Cancelado'), ('UNKNOWN', 'Desconhecido')], default='UNKNOWN', max_length=16)),
                ('payment_type', models.CharField(blank=True, default='', max_length=64)),
                ('raw_extras', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'indexes': [models.Index(fields=['organization', 'status', 'due_date'], name='financial_e_organiz_4207b3_idx'), models.Index(fields=['organization', 'paid_at'], name='financial_e_organiz_8ea811_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_type', 'external_id'), name='unique_expense_per_source')],
            },
        ),
    ]
