# Generated by Django 5.2.14 on 2026-06-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_historicalexpense_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete: setado pela reconciliação quando o registro some do IXC (fonte da verdade). Nunca removemos fisicamente — só marcamos.', null=True),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete: setado pela reconciliação quando o registro some do IXC (fonte da verdade). Nunca removemos fisicamente — só marcamos.', null=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete: setado pela reconciliação quando o registro some do IXC (fonte da verdade). Nunca removemos fisicamente — só marcamos.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete: setado pela reconciliação quando o registro some do IXC (fonte da verdade). Nunca removemos fisicamente — só marcamos.', null=True),
        ),
    ]
