# Generated by Django 5.2.14 on 2026-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_expense_deleted_at_historicalexpense_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
    ]
