# Generated by Django 5.2.14 on 2026-05-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_historicalcontract_contract'),
        ('financial', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('plan_name', models.CharField(max_length=128)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=24)),
                ('current', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Dim Contract',
                'verbose_name_plural': 'Dim Contracts',
                'indexes': [models.Index(fields=['organization', 'source_type', 'external_id', 'current'], name='analytics_d_organiz_861ed7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DimCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('IXC', 'IXC Soft'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('document', models.CharField(db_index=True, max_length=14)),
                ('status', models.CharField(max_length=16)),
                ('current', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Dim Customer',
                'verbose_name_plural': 'Dim Customers',
                'indexes': [models.Index(fields=['organization', 'source_type', 'external_id', 'current'], name='analytics_d_organiz_4fbcfe_idx'), models.Index(fields=['organization', 'document'], name='analytics_d_organiz_2e2b15_idx')],
            },
        ),
        migrations.CreateModel(
            name='DimPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Dim Plan',
                'verbose_name_plural': 'Dim Plans',
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_dim_plan_per_org')],
            },
        ),
        migrations.CreateModel(
            name='FactContractStatusDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(max_length=24)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_daily', to='customers.contract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Fato: contrato/status diário',
                'verbose_name_plural': 'Fatos: contratos/status diário',
                'indexes': [models.Index(fields=['organization', 'date', 'is_active'], name='analytics_f_organiz_71e99d_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'contract', 'date'), name='unique_fact_contract_status_per_day')],
            },
        ),
        migrations.CreateModel(
            name='FactInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(db_index=True)),
                ('paid_date', models.DateField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(max_length=16)),
                ('days_overdue', models.IntegerField(default=0)),
                ('aging_bucket', models.CharField(default='ON_TIME', max_length=16)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact', to='financial.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Fato: fatura',
                'verbose_name_plural': 'Fatos: faturas',
                'indexes': [models.Index(fields=['organization', 'status', 'aging_bucket'], name='analytics_f_organiz_8eacf0_idx'), models.Index(fields=['organization', 'due_date'], name='analytics_f_organiz_674bd0_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'invoice'), name='unique_fact_invoice')],
            },
        ),
        migrations.CreateModel(
            name='FactPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact', to='financial.payment')),
            ],
            options={
                'verbose_name': 'Fato: pagamento',
                'verbose_name_plural': 'Fatos: pagamentos',
                'indexes': [models.Index(fields=['organization', 'paid_date'], name='analytics_f_organiz_44ef05_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'payment'), name='unique_fact_payment')],
            },
        ),
    ]
