# Generated by Django 5.2.14 on 2026-05-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('financial', '0002_historicalexpense_expense'),
        ('tenancy', '0002_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField(db_index=True)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact', to='financial.expense')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Fato: despesa',
                'verbose_name_plural': 'Fatos: despesas',
                'indexes': [models.Index(fields=['organization', 'expense_date'], name='analytics_f_organiz_ca484b_idx'), models.Index(fields=['organization', 'status'], name='analytics_f_organiz_9c5abe_idx'), models.Index(fields=['organization', 'category'], name='analytics_f_organiz_127f33_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'expense'), name='unique_fact_expense')],
            },
        ),
    ]
