# Generated by Django 5.2.14 on 2026-05-29 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_factexpense'),
        ('tenancy', '0002_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContasCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_map', models.JSONField(default=dict, help_text='id_planejamento → {cod, nome, tipo} — da tabela `planejamento` do IXC', verbose_name='Mapa de planejamento')),
                ('conta_map', models.JSONField(default=dict, help_text='planejamento_analitico.id → id_planejamento — da tabela `planejamento_analitico` do IXC', verbose_name='Mapa de contas analíticas')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_contas_cache', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Cache do plano de contas IXC',
                'verbose_name_plural': 'Caches do plano de contas IXC',
            },
        ),
    ]
