# Generated by Django 5.2.14 on 2026-06-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_plano_contas_cache'),
        ('customers', '0003_add_addon_discount_amounts'),
        ('tenancy', '0007_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('level', models.CharField(choices=[('HIGH', 'Alto'), ('MEDIUM', 'Médio'), ('LOW', 'Baixo')], db_index=True, max_length=8)),
                ('signals', models.JSONField(default=list)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computed_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='churn_risk_scores', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Score de risco de churn',
                'verbose_name_plural': 'Scores de risco de churn',
                'indexes': [models.Index(fields=['organization', '-score'], name='analytics_c_organiz_c4db6b_idx'), models.Index(fields=['organization', 'level'], name='analytics_c_organiz_102d0c_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'customer'), name='unique_churn_risk_per_customer')],
            },
        ),
    ]
