# Generated by Django 5.2.14 on 2026-06-02 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_churnriskscore'),
        ('tenancy', '0008_historicaluser_churn_digest_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churnriskscore',
            name='ml_probability',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ChurnRiskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_names', models.JSONField(default=list)),
                ('weights', models.JSONField(default=dict)),
                ('bias', models.FloatField(default=0.0)),
                ('feature_means', models.JSONField(default=dict)),
                ('feature_stds', models.JSONField(default=dict)),
                ('n_samples', models.PositiveIntegerField(default=0)),
                ('n_positive', models.PositiveIntegerField(default=0)),
                ('train_accuracy', models.FloatField(default=0.0)),
                ('trained_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Modelo de risco de churn',
                'verbose_name_plural': 'Modelos de risco de churn',
                'constraints': [models.UniqueConstraint(fields=('organization',), name='unique_churn_model_per_org')],
            },
        ),
    ]
