# Generated by Django 5.2.14 on 2026-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_churnriskscore_ml_probability_churnriskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='churnriskmodel',
            name='val_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churnriskmodel',
            name='val_auc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
