# Generated by Django 5.2.14 on 2026-06-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_churnriskmodel_val_accuracy_churnriskmodel_val_auc'),
        ('tenancy', '0008_historicaluser_churn_digest_monthly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_map', models.JSONField(default=dict, help_text='id_fornecedor → nome — da tabela `fornecedor` do IXC', verbose_name='Mapa de fornecedores')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_cache', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Cache de fornecedores IXC',
                'verbose_name_plural': 'Caches de fornecedores IXC',
            },
        ),
    ]
