# Generated by Django 5.2.14 on 2026-06-02 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_fornecedorcache'),
        ('tenancy', '0008_historicaluser_churn_digest_monthly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactNetworkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('total_count', models.IntegerField(default=0)),
                ('online_count', models.IntegerField(default=0)),
                ('offline_count', models.IntegerField(default=0)),
                ('blocked_count', models.IntegerField(default=0)),
                ('unknown_count', models.IntegerField(default=0)),
                ('uptime_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('rx_bytes_total', models.BigIntegerField(default=0)),
                ('tx_bytes_total', models.BigIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Fato: snapshot de rede',
                'verbose_name_plural': 'Fatos: snapshots de rede',
                'indexes': [models.Index(fields=['organization', 'captured_at'], name='analytics_f_organiz_749ec5_idx')],
            },
        ),
    ]
