# Generated by Django 5.2.14 on 2026-06-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_factnetworksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='factinvoice',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
