# Generated by Django 5.2.14 on 2026-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_factinvoice_late_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimcontract',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='dimcustomer',
            name='source_type',
            field=models.CharField(choices=[('IXC', 'IXC Soft'), ('OPA', 'Opa! Suite'), ('SGP', 'SGP'), ('CONTAAZUL', 'Conta Azul'), ('CSV', 'CSV upload'), ('FAKE', 'Fake (testes)')], max_length=32),
        ),
    ]
