# Generated by Django 5.2.14 on 2026-06-09 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_dimcontract_source_type_and_more'),
        ('atendimento', '0001_initial'),
        ('tenancy', '0009_alter_historicalorganizationdatasource_capability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolveu', models.BooleanField(default=False)),
                ('sla_ok', models.BooleanField(default=False)),
                ('tom', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('empatia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aderencia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('categoria', models.CharField(blank=True, default='', max_length=64)),
                ('resumo', models.TextField(blank=True, default='')),
                ('melhoria', models.TextField(blank=True, default='')),
                ('atendente_external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('atendente_nome', models.CharField(blank=True, default='', max_length=255)),
                ('model_name', models.CharField(blank=True, default='', max_length=64)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField()),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_reviews', to='atendimento.atendimento')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Avaliação de QA de atendimento',
                'verbose_name_plural': 'Avaliações de QA de atendimento',
                'indexes': [models.Index(fields=['organization', '-overall_score'], name='analytics_q_organiz_76f897_idx'), models.Index(fields=['organization', 'atendente_external_id'], name='analytics_q_organiz_4fe83e_idx'), models.Index(fields=['organization', 'reviewed_at'], name='analytics_q_organiz_25e484_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'atendimento'), name='unique_qa_review_per_atendimento')],
            },
        ),
    ]
