# Generated by Django 5.2.14 on 2026-08-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_factctosnapshot_timestamps'),
        ('customers', '0004_alter_contract_source_type_and_more'),
        ('tenancy', '0011_organizationinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactChurnRiskDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('level', models.CharField(choices=[('HIGH', 'Alto'), ('MEDIUM', 'Médio'), ('LOW', 'Baixo')], db_index=True, max_length=8)),
                ('signals', models.JSONField(default=list)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ml_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Histórico diário de risco de churn',
                'verbose_name_plural': 'Histórico diário de risco de churn',
            },
        ),
        migrations.RenameIndex(
            model_name='factctosnapshot',
            new_name='analytics_f_organiz_405055_idx',
            old_name='factcto_org_captured_idx',
        ),
        migrations.AlterField(
            model_name='factctosnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='factchurnriskdaily',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_risk_history', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='factchurnriskdaily',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização'),
        ),
        migrations.AddIndex(
            model_name='factchurnriskdaily',
            index=models.Index(fields=['organization', 'date'], name='analytics_f_organiz_59ecad_idx'),
        ),
        migrations.AddIndex(
            model_name='factchurnriskdaily',
            index=models.Index(fields=['organization', 'date', 'level'], name='analytics_f_organiz_d04978_idx'),
        ),
        migrations.AddConstraint(
            model_name='factchurnriskdaily',
            constraint=models.UniqueConstraint(fields=('organization', 'customer', 'date'), name='unique_churn_risk_daily'),
        ),
    ]
