# Generated by Django 5.2.14 on 2026-09-20 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_churn_risk_daily'),
        ('tenancy', '0016_alter_displaydevice_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnBacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('d0', models.DateField(help_text='Data avaliada — a foto da base que o backtest usou.')),
                ('horizon_days', models.PositiveIntegerField(help_text='Janela de desfecho: cancelou até D0 + N dias.')),
                ('base_size', models.PositiveIntegerField(default=0)),
                ('canceled', models.PositiveIntegerField(default=0)),
                ('base_rate', models.FloatField(default=0.0, help_text='Taxa de cancelamento da base inteira — o acaso a superar.')),
                ('signals', models.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Backtest de churn',
                'verbose_name_plural': 'Backtests de churn',
                'indexes': [models.Index(fields=['organization', '-d0'], name='analytics_c_organiz_a83f76_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'd0', 'horizon_days'), name='unique_churn_backtest_run')],
            },
        ),
    ]
