# Generated by Django 5.2.14 on 2026-05-28 19:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAssumption',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('key', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=6, max_digits=14)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(default='%', max_length=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'historical Premissa',
                'verbose_name_plural': 'historical Premissas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalScenario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('type', models.CharField(choices=[('PJ_VS_CLT', 'PJ vs CLT'), ('SALARY_ADJUST', 'Ajuste salarial'), ('UNION_ESP', 'Sindicato ESP'), ('SIMPLES_SPLIT', 'Split CNPJ — Simples Nacional')], max_length=24)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('inputs', models.JSONField(default=dict)),
                ('results', models.JSONField(default=dict)),
                ('base_at', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'historical Cenário',
                'verbose_name_plural': 'historical Cenários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=6, max_digits=14)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(default='%', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Premissa',
                'verbose_name_plural': 'Premissas',
                'indexes': [models.Index(fields=['organization', 'key'], name='scenarios_a_organiz_a7c88b_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='unique_assumption_per_org')],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PJ_VS_CLT', 'PJ vs CLT'), ('SALARY_ADJUST', 'Ajuste salarial'), ('UNION_ESP', 'Sindicato ESP'), ('SIMPLES_SPLIT', 'Split CNPJ — Simples Nacional')], max_length=24)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('inputs', models.JSONField(default=dict)),
                ('results', models.JSONField(default=dict)),
                ('base_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Cenário',
                'verbose_name_plural': 'Cenários',
                'indexes': [models.Index(fields=['organization', 'type', '-base_at'], name='scenarios_s_organiz_860a60_idx')],
            },
        ),
    ]
